apiVersion: v1
kind: Service
metadata:
  name: php-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: php
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - protocol: TCP
      name: php
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: php
  name: php-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: php
  template: 
    metadata: 
      labels: 
        app: php
    spec: 
      containers:
        - 
          image: php_image
          imagePullPolicy: Never
          name: php
          ports: 
            - containerPort: 5000
